/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.onner.form;

import com.onner.async.ProcessButtons;
import com.onner.async.ProcessClickMe;
import com.onner.global.Global;

/**
 *
 * @author lionos
 */
public class Space extends javax.swing.JFrame {
    private ProcessButtons processButtons;
    private ProcessClickMe processClickMe;
    private Thread processThreadGame;

    public Space() {
        initComponents();
        initGeneral();
    }

    private void initGeneral() {
        this.setLocationRelativeTo(null);
        ButtonSpace.setLayout(null);
        playTheGame.setFocusPainted(false);
        playTheGame.setBorderPainted(false);

        processClickMe = new ProcessClickMe();
        processButtons = new ProcessButtons(this.CounterTime, this.ButtonSpace, processClickMe);
        processThreadGame = new Thread(processButtons);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        playspace = new javax.swing.JPanel();
        PlayersSpace = new javax.swing.JPanel();
        Player = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CounterTimeSpace = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CounterTime = new javax.swing.JLabel();
        ButtonSpace = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        playTheGame = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playspace.setBackground(new java.awt.Color(252, 194, 52));
        playspace.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PlayersSpace.setBackground(new java.awt.Color(203, 132, 28));
        PlayersSpace.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(146, 76, 1), 3));
        PlayersSpace.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Player.setBackground(new java.awt.Color(236, 222, 152));
        Player.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 103, 22), 2));
        Player.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(117, 80, 154));
        jLabel3.setText("Jugador");
        Player.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(56, 203, 35));
        jLabel5.setText("Lanchito");
        Player.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 23, -1, 40));

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(29, 158, 249));
        jLabel6.setText("PTS");
        Player.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 40, 30));

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(29, 158, 249));
        jLabel7.setText("10");
        Player.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 60, 50));

        PlayersSpace.add(Player, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 70));

        playspace.add(PlayersSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 250, 470));

        CounterTimeSpace.setBackground(new java.awt.Color(191, 164, 19));
        CounterTimeSpace.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 121, 40), 5));
        CounterTimeSpace.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(252, 255, 255));
        jLabel2.setText("Cambia en:");
        CounterTimeSpace.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 50));

        CounterTime.setFont(new java.awt.Font("Noto Sans", 1, 48)); // NOI18N
        CounterTime.setForeground(new java.awt.Color(252, 255, 255));
        CounterTime.setText("5");
        CounterTimeSpace.add(CounterTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 30, 50));

        playspace.add(CounterTimeSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 220, 70));

        ButtonSpace.setBackground(new java.awt.Color(99, 66, 14));
        ButtonSpace.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(181, 120, 22), 5));
        ButtonSpace.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        playspace.add(ButtonSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 670, 470));

        jLabel1.setText("FIfigagasdfasd");
        playspace.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 80));

        playTheGame.setBackground(new java.awt.Color(56, 203, 35));
        playTheGame.setFont(new java.awt.Font("Noto Sans", 1, 36)); // NOI18N
        playTheGame.setForeground(new java.awt.Color(255, 255, 255));
        playTheGame.setText("Jugar");
        playTheGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                playTheGameMousePressed(evt);
            }
        });
        playspace.add(playTheGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 180, 50));

        getContentPane().add(playspace, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playTheGameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playTheGameMousePressed
        // TODO add your handling code here:
        if (Global.stateOfPlay) {
            playTheGame.setEnabled(true);

            processButtons.stop();
            Global.stateOfPlay = false;
            playTheGame.setText("PLAY");
        } else {
            this.playTheGame.setEnabled(false);

            processButtons = new ProcessButtons(this.CounterTime, this.ButtonSpace, processClickMe);
            processThreadGame = new Thread(processButtons);
            processThreadGame.start();
            Global.stateOfPlay = true;
            playTheGame.setText("STOP");
        }
    }//GEN-LAST:event_playTheGameMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Space.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Space.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Space.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Space.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Space().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonSpace;
    private javax.swing.JLabel CounterTime;
    private javax.swing.JPanel CounterTimeSpace;
    private javax.swing.JPanel Player;
    private javax.swing.JPanel PlayersSpace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton playTheGame;
    private javax.swing.JPanel playspace;
    // End of variables declaration//GEN-END:variables
}
